name: Deploy static site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare static site
        run: |
          mkdir public
          cp index.html styles.css script.js public/
      - name: Deploy to gh-pages
        uses: hyoo-ru/gh-deploy@v4.4.1
        with:
          folder: public
